### ISSUE TITLE
Is UGUI objects supported

### ISSUE THREAD

**Issue by sekkit** [ndepoel/FSR2Unity#11]
I noticed UGUI's button is not affected by FSR3 when observing with eyes.
Is ugui object upscaled by fsr3?
and how could I determine the actual rendered resolution?

**Comment by ndepoel** [comment]
Hi,

This is expected and is what you'll typically want. FSR2/3 Upscaling is meant to be used only on 3D elements in the scene, while you'll want 2D UI elements to be rendered at full native resolution. This is what most games with dynamic resolution scaling do, in order to keep the UI sharp and crisp. This happens naturally with FSR2/3 Upscaling because the upscaling component is applied to the 3D scene camera, while UI is handled separately and gets drawn after the 3D scene camera is done.

The actual internal rendering resolution is logged by the FSR3 Upscaler component when it is initialized. Looks for a line in the log saying "Setting up FSR3 Upscaler with render size: 1280x720, display size: 1920x1080" or similar. This line gets logged any time you change the FSR quality mode as well, or any other setting that requires a restart of FSR's systems.

There is also a function in the Fsr3Upscaler class named GetRenderResolutionFromQualityMode that will return the expected render resolution, given a display resolution and quality mode as inputs.
